In [1]:
a = {}

In [2]:
a[33] = 3

In [3]:
a

{33: 3}

In [4]:
33 in a

True

In [5]:
3 in a

False

In [6]:
import numpy as np

def merge_maps(map1, ref1, map2, ref2, fill_value=0):
    h1, w1 = map1.shape
    h2, w2 = map2.shape

    # Offset of map2 relative to map1
    dy = ref1[0] - ref2[0]
    dx = ref1[1] - ref2[1]

    # Compute the top-left and bottom-right corners of the final map
    top = min(0, dy)
    left = min(0, dx)
    bottom = max(h1, dy + h2)
    right = max(w1, dx + w2)

    H = bottom - top
    W = right - left

    combined_map = np.full((H, W), fill_value, dtype=map1.dtype)

    # Paste map1
    y1_offset = -top
    x1_offset = -left
    combined_map[y1_offset:y1_offset + h1, x1_offset:x1_offset + w1] = map1

    # Paste map2
    y2_offset = y1_offset + dy
    x2_offset = x1_offset + dx
    combined_map[y2_offset:y2_offset + h2, x2_offset:x2_offset + w2] = map2

    return combined_map


In [14]:
map1 = np.array([
    [0,0,1,1,1,0],
    [0,0,1,1,1,0],
    [0,0,1,1,10,0],
    [0,0,1,1,1,0],
])

map2 = np.array([
    [0,0,1,1,1,0],
    [0,0,1,20,1,0],
    [0,0,1,1,1,0],
    [0,0,1,1,1,0],
]) + 3

In [15]:
map1

array([[ 0,  0,  1,  1,  1,  0],
       [ 0,  0,  1,  1,  1,  0],
       [ 0,  0,  1,  1, 10,  0],
       [ 0,  0,  1,  1,  1,  0]])

In [16]:
map2

array([[ 3,  3,  4,  4,  4,  3],
       [ 3,  3,  4, 23,  4,  3],
       [ 3,  3,  4,  4,  4,  3],
       [ 3,  3,  4,  4,  4,  3]])

In [20]:
ref1 = coords_of_1_in_map_1 = (2,4)
ref2 = coords_of_1_in_map_2 = (0,3)

In [23]:
res = merge_maps(map1, ref1, np.ones_like(map2)*7, ref2, fill_value=0)

In [24]:
res

array([[0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 7, 7, 7, 7, 7, 7],
       [0, 7, 7, 7, 7, 7, 7],
       [0, 7, 7, 7, 7, 7, 7],
       [0, 7, 7, 7, 7, 7, 7]])